# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtWidgets,QtGui
import ler_arquivo as la
import main
from PyQt5.QtCore import QThread, QObject
from os import environ


def suppress_qt_warnings():
    environ["QT_DEVICE_PIXEL_RATIO"] = "0"
    environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    environ["QT_SCREEN_SCALE_FACTORS"] = "1"
    environ["QT_SCALE_FACTOR"] = "1"


class Faz_Backup(QObject):

    def __init__(self, parent=None):
        QObject.__init__(self, parent=parent)

    def iniciar_bkp(self):
        main.faz_backup()


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(708, 589)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("backup.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.textLog = QtWidgets.QTextBrowser(Form)
        self.textLog.setGeometry(QtCore.QRect(10, 180, 681, 381))
        self.textLog.setObjectName("textLog")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(330, 20, 341, 133))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbHr_iniciar_bkp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lbHr_iniciar_bkp.setObjectName("lbHr_iniciar_bkp")
        self.verticalLayout_6.addWidget(self.lbHr_iniciar_bkp)
        self.lbHr_para_bkp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lbHr_para_bkp.setObjectName("lbHr_para_bkp")
        self.verticalLayout_6.addWidget(self.lbHr_para_bkp)
        self.lbTempo_entre_bkp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lbTempo_entre_bkp.setObjectName("lbTempo_entre_bkp")
        self.verticalLayout_6.addWidget(self.lbTempo_entre_bkp)
        self.lbDias_manter_bkp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lbDias_manter_bkp.setObjectName("lbDias_manter_bkp")
        self.verticalLayout_6.addWidget(self.lbDias_manter_bkp)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSalvar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSalvar.setObjectName("btnSalvar")
        self.horizontalLayout.addWidget(self.btnSalvar)
        self.btnIniciar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnIniciar.setObjectName("btnIniciar")
        self.horizontalLayout.addWidget(self.btnIniciar)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(20, 160, 47, 14))
        self.label_15.setObjectName("label_15")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 20, 301, 128))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbInstancia = QtWidgets.QLineEdit(self.widget)
        self.lbInstancia.setObjectName("lbInstancia")
        self.verticalLayout_2.addWidget(self.lbInstancia)
        self.lbLogin = QtWidgets.QLineEdit(self.widget)
        self.lbLogin.setObjectName("lbLogin")
        self.verticalLayout_2.addWidget(self.lbLogin)
        self.lbSenha = QtWidgets.QLineEdit(self.widget)
        self.lbSenha.setObjectName("lbSenha")
        self.verticalLayout_2.addWidget(self.lbSenha)
        self.lbDatabase = QtWidgets.QLineEdit(self.widget)
        self.lbDatabase.setObjectName("lbDatabase")
        self.verticalLayout_2.addWidget(self.lbDatabase)
        self.lbCaminho = QtWidgets.QLineEdit(self.widget)
        self.lbCaminho.setObjectName("lbCaminho")
        self.verticalLayout_2.addWidget(self.lbCaminho)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.carrega_dados_arq()
        main.recovery_full()

        """
        # Thread do Log
        self.thread_log = QThread()
        self.ler_log = Le_Logs()
        self.ler_log.moveToThread(self.thread_log)
        self.thread_log.started.connect(self.ler_log.cria_log)
        """
        # Thread do Backup
        self.thread_bkp = QThread()
        self.fazer_bkp = Faz_Backup()
        self.fazer_bkp.moveToThread(self.thread_bkp)
        self.thread_bkp.started.connect(self.fazer_bkp.iniciar_bkp)



        self.btnSalvar.clicked.connect(self.salvar_dados)
        self.btnIniciar.clicked.connect(self.thread_bkp.start)
        self.btnSalvar.clicked.connect(self.cria_log)
        self.btnIniciar.clicked.connect(self.btn_iniciar)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Backup"))
        self.textLog.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.label_11.setText(_translate("Form", "HORA INICIAR BKP:"))
        self.label_12.setText(_translate("Form", "HORA PARA BKP:"))
        self.label_13.setText(_translate("Form", "TEMPO ENTRE BKP:"))
        self.label_14.setText(_translate("Form", "DIAS MANTER BACKUP:"))
        self.btnSalvar.setText(_translate("Form", "SALVAR"))
        self.btnIniciar.setText(_translate("Form", "INICIAR"))
        self.label_15.setText(_translate("Form", "LOG:"))
        self.label.setText(_translate("Form", "INSTANCIA:"))
        self.label_2.setText(_translate("Form", "LOGIN:"))
        self.label_3.setText(_translate("Form", "SENHA:"))
        self.label_4.setText(_translate("Form", "DATABASE:"))
        self.label_5.setText(_translate("Form", "CAMINHO:"))

    def salvar_dados(self):
        """
        def escreve_arquivo(server, username, password, database_bck, local_bkp, hr_inicio_bkp, hr_final_bkp,
                    tempo_bkp_log, dias_manter_bkp):
        """
        try:
            la.escreve_arquivo(self.lbInstancia.text(), self.lbLogin.text(), self.lbSenha.text(), self.lbDatabase.text(),
                               self.lbCaminho.text(), self.lbHr_iniciar_bkp.text(), self.lbHr_para_bkp.text(),
                               self.lbTempo_entre_bkp.text(), self.lbDias_manter_bkp.text())

            self.textLog.append('\nDADOS SALVOS COM SUCESSO')
        except:
            self.textLog.append('\nALGO DEU ERRADO AO SALVOR OS DADOS')

    def carrega_dados_arq(self):
        """
        retorno = {'server' : server, 'login' : username, 'senha' : password, 'local_bkp_original' : local_org,
               'database' : database_bck, 'hr_inicio_bkp' : hr_inicio_bkp, 'hr_final_bkp' : hr_final_bkp,
               'tempo_bkp_log' : tempo_bkp_log, 'dias_manter_bkp' : dias_manter_bkp, 'local_bkp' : local_bkp}
        """
        self.lbInstancia.setText(la.ler_variaveis()['server'])
        self.lbLogin.setText(la.ler_variaveis()['login'])
        self.lbSenha.setText(la.ler_variaveis()['senha'])
        self.lbDatabase.setText(la.ler_variaveis()['database'])
        self.lbCaminho.setText(la.ler_variaveis()['local_bkp_original'])
        self.lbHr_iniciar_bkp.setText(la.ler_variaveis()['hr_inicio_bkp'])
        self.lbHr_para_bkp.setText(la.ler_variaveis()['hr_final_bkp'])
        self.lbTempo_entre_bkp.setText(la.ler_variaveis()['tempo_bkp_log'])
        self.lbDias_manter_bkp.setText(la.ler_variaveis()['dias_manter_bkp'])

    def btn_iniciar(self):
        self.textLog.append('\nROTINA DE BACKUP INICIADA')

    def cria_log(self):
        self.textLog.setText(la.le_log())


if __name__ == '__main__':
    suppress_qt_warnings()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

